name: PHP app
on: [push]
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: phpunit, composer
          extensions: zip
      - name: Create .env file
        run: |
          echo "DB_URL=${{secrets.DB_URL_PHP}}" >> .env
          echo "DB_USERNAME=${{secrets.DB_USERNAME_PHP}}" >> .env
          echo "DB_PASSWORD=${{secrets.DB_PASSWORD_PHP}}" >> .env
      - name: Install Dotenv
        run: composer require vlucas/phpdotenv
      - name: Run test
        run: phpunit ./tests/unit/IngredientTest.php

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:php_app
          build-args: |
            DB_URL=${{ secrets.DB_URL_PHP }}
            DB_USERNAME=${{ secrets.DB_USERNAME_PHP }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD_PHP }}
